<a href="https://colab.research.google.com/github/Elisabeth-Engering/github-slideshow/blob/main/DeepLearning/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print ("Execute this cell to verify you are connected to the runtime environment successfully")

Execute this cell to verify you are connected to the runtime environment successfully


In [4]:
#import tensorflow as tf
import tensorflow as tf
print(tf.__version__)

2.8.0


_Everything in TensorFlow is based on Tensor operations.
Tensors are (kind of) like np.arrays.
All tensors are immutable: you can never update the contents of a tensor, only create a new one._

Don't forget to refer to Tensor documentation from TensorFlow

https://www.tensorflow.org/guide/tensor#tfconvert_to_tensor


**1. Create Tensors - Add your answer below the questions(comments)**

In [11]:
#Example on how to answer these comments

# scalar with value 8, rank-0 tensor
x = tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [69]:
# scalar with any value and data type float32, rank-0 tensor
x = tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float32)
print(x)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [70]:
# create a tensor with these values 
# tf.Tensor(4, shape=(1, 1), dtype=float32)
x = tf.constant([[4]], dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
# create a tensor as a vector, rank-1, with values 1,2,3
x = tf.constant([1,2,3])
print(x)

In [ ]:
# create a tensor with these values 
# tf.Tensor([[1 2 3] [4 5 6]], shape=(2, 3), dtype=int32)
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

In [74]:
# create a tensor with shape = 3x3, with all 9 elements = 0 
y = tf.zeros((3,3))
print(y)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [75]:
# create a tensor with shape = 3x3, with all 9 elements = 1 
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [76]:
# create a tensor with shape = 3x3, representing an identity matrix 
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [77]:
# create a tensor with shape = 3x3, filled with random values. The values should be normal distributed with mean=5, and standard deviation=2
x = tf.random.normal([3,3], 5, 2)
print(x)
# or
x = tf.random.normal((3,3), mean=5, stddev=2)
print(x)

tf.Tensor(
[[5.451225  3.1871614 8.47667  ]
 [5.714191  4.2536993 4.954877 ]
 [8.176823  5.21314   4.375807 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[6.251859   4.087904   0.92807055]
 [4.8947783  7.3459406  6.9680986 ]
 [3.6432533  1.0950723  6.7576666 ]], shape=(3, 3), dtype=float32)


In [19]:
# create a tensor with shape = 3x3, filled with random values. The values should be uniformly distributed in range of -1 to 1
x = tf.random.uniform(shape=[3,3], minval=-1, maxval=1)
print(x)

tf.Tensor(
[[ 0.6928692   0.5050733  -0.57175255]
 [-0.43856382  0.34311652  0.15577936]
 [-0.6101463   0.01781178 -0.54022217]], shape=(3, 3), dtype=float32)


In [78]:
# create a tensor with tf.range, that will represnt this:
# tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
start = 0
limit = 10
delta = 1
x = tf.range(start, limit, delta)
print(x)
# or
x = tf.range(start=0, limit=10,delta=1)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [80]:
# create a tensor with tf.range, that will represnt a list of all even numbers between 1 & 11. Then change the data type to float32 using tf.cast
start = 2
limit = 12
delta = 2
x = tf.range(start, limit, delta)
x = tf.cast(x, tf.float32)
print(x)
# or
x = tf.range(start=2, limit=12,delta=2)
x = tf.cast(x, tf.float32)
print(x)

tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)
tf.Tensor([ 2.  4.  6.  8. 10.], shape=(5,), dtype=float32)


**2. Mathmatical operations with Tensor - Add your answer below the questions(comments)**

In [82]:
# Here are 2 tensors
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

In [83]:
# Add x and y using both tf.add and "+" operator. Note, both techniques are exactly same performance wise
print(tf.add(x, y))
# or
print(x + y)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [84]:
# write code for (x-y)
print(tf.subtract(x,y))
# or
print(x - y)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [85]:
# Do z = 1 / y and then element wise multiply z to x using tf.multiply 
z = 1 / y
z = z * tf.cast(x, dtype=tf.double)
print(z)

a = tf.multiply(z,x)
print(a)

In [88]:
# matrix multiplication 
x = tf.random.normal((2,2)) 
y = tf.random.normal((3,4)) 

# correct the shape of y matrix such that it can be multiplied to x matrix
reshaped_y = tf.reshape(y, [2,6])

# Write code to multiply 2 matrices x and y
z = tf.matmul(x,reshaped_y)
print(z)

tf.Tensor(
[[-0.15130015 -0.60648984 -0.3932451   0.62908304  0.3450277   0.30399925]
 [ 0.00989947 -0.5024148  -0.01669383  0.5913449   0.28160307 -0.43250507]], shape=(2, 6), dtype=float32)


**3. Indexing and Slicing - Add your answer below the questions(comments)**

For reference : https://sodocumentation.net/tensorflow/topic/2511/tensor-indexing


In [89]:
# x has shape 2 rows with 4 columns
x = tf.constant([[1,2,3,4],
                 [5,6,7,8]])

# Print all elements from first row 
print(x[0])

# Print elements from all rows, column 0
print(x[:, 0])

# print elements from row 1, all columns
print(x[1, :])

# Print element "6" from x
print(x[1,1])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [92]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
# print all 8 elements from x
print(x[:])

# print all elements from x, without the first element
print(x[1:])

# print tf.Tensor([1 1], shape=(2,), dtype=int32) from tensor x
x = tf.constant([1,1])
print(x)

# print all elements at odd indeces in x
print(x[::2])

# print all elements in x in reverse order
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


In [93]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
indices = tf.constant([0, 3])
# use tf.gather to print the elements in x at indexes given in indices list
x_indices = tf.gather(x, indices)
print(x_indices)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [94]:
x = tf.constant([
                 [1, 2], 
                 [3, 4], 
                 [5, 6]])

# print all elements from first row
print(x[0, :])

# print all elements from first 2 rows only
print(x[0:2, :])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


**3. Reshape - Add your answer below the questions(comments)**

In [66]:
x = tf.random.normal((2,3))
print(x)

#reshape x to shape = 3,2
x = tf.reshape(x, [3,2])
print(x)

#reshape x to shape = 6
x = tf.reshape(x, [6])
print(x)

tf.Tensor(
[[ 0.76771855  0.08923824  0.04105416]
 [-1.1116366  -0.4614231   0.18090379]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.76771855  0.08923824]
 [ 0.04105416 -1.1116366 ]
 [-0.4614231   0.18090379]], shape=(3, 2), dtype=float32)
tf.Tensor([ 0.76771855  0.08923824  0.04105416 -1.1116366  -0.4614231   0.18090379], shape=(6,), dtype=float32)


**4. Convert numpy to tensor**

In [67]:
# 6. numpy
x = x.numpy()
print(type(x))

x = tf.convert_to_tensor(x)
print(type(x))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
