<a href="https://colab.research.google.com/github/Elisabeth-Engering/github-slideshow/blob/main/DeepLearning/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Execute this cell to verify you are connected to the runtime environment successfully")

Execute this cell to verify you are connected to the runtime env. successfully


In [ ]:
#import tensorflow as tf
import tensorflow as tf
print(tf.__version__)

2.7.0


_Everything in TensorFlow is based on Tensor operations.
Tensors are (kind of) like np.arrays.
All tensors are immutable: you can never update the contents of a tensor, only create a new one._

Don't forget to refer to Tensor documentation from TensorFlow

https://www.tensorflow.org/guide/tensor#tfconvert_to_tensor


**1. Create Tensors - Add your answer below the questions(comments)**

In [ ]:
#Example on how to answer these comments


# scalar with value 8, rank-0 tensor
x = tf.constant(4)
print(x)

In [ ]:
# scalar with any value and data type float32, rank-0 tensor

In [ ]:
# create a tensor with these values 
# tf.Tensor([[4.]], shape=(1, 1), dtype=float32)

In [ ]:
# create a tensor as a vector, rank-1, with values 1,2,3

In [ ]:
# create a tensor with these values 
# tf.Tensor([[1 2 3] [4 5 6]], shape=(2, 3), dtype=int32)

In [ ]:
# create a tensor with shape = 3x3, with all 9 elements = 0 

In [ ]:
# create a tensor with shape = 3x3, with all 9 elements = 1 

In [ ]:
# create a tensor with shape = 3x3, representing an identity matrix 

In [ ]:
# create a tensor with shape = 3x3, filled with random values. The values should be normal distributed with mean=5, and standard deviation=2

In [ ]:
# create a tensor with shape = 3x3, filled with random values. The values should be uniformly distributed in range of -1 to 1

In [ ]:
# create a tensor with tf.range, that will represnt this:
# tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)

In [ ]:
# create a tensor with tf.range, that will represnt a list of all even numbers between 1 & 11. Then change the data type to float32 using tf.cast

**2. Mathmatical operations with Tensor - Add your answer below the questions(comments)**

In [ ]:
# Here are 2 tensors
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

In [ ]:
# Add x and y using both tf.add and "+" operator. Note, both techniques are exactly same performance wise

In [ ]:
# write code for (x-y)

In [ ]:
# Do
# z = 1 / y and then element wise multiply z to x using tf.multiply 

In [ ]:
# matrix multiplication 
x = tf.random.normal((2,2)) 
y = tf.random.normal((3,4)) # correct the shape of y matrix such that it can be multiplied to x matrix


# Write code to multiply 2 matrices x and y

**3. Indexing and Slicing - Add your answer below the questions(comments)**

For reference : https://sodocumentation.net/tensorflow/topic/2511/tensor-indexing


In [ ]:
# x has shape 2 rows with 4 columns
x = tf.constant([
                 [1,2,3,4],
                 [5,6,7,8]])

# Print all elements from first row 
print(x[0])

# Print elements from all rows, column 0
# print elements from row 1, all columns
# Print element "6" from x

In [ ]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
# print all 8 elements from x
print(x[:])

# print all elements from x, without the first element
# print tf.Tensor([1 1], shape=(2,), dtype=int32) from tensor x
# print all elements at odd indeces in x
# print all elements in x in reverse order

In [ ]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
indices = tf.constant([0, 3])
# use tf.gather to print the elements in x at indexes given in indices list

In [ ]:
x = tf.constant([
                 [1, 2], 
                 [3, 4], 
                 [5, 6]])

# print all elements from first row
# print all elements from first 2 rows only

**3. Reshape - Add your answer below the questions(comments)**

In [ ]:
x = tf.random.normal((2,3))
print(x)

#reshape x to shape = 3,2

#reshape x to shape = 6


**4. Convert numpy to tensor**

In [ ]:
# 6. numpy
x = x.numpy()
print(type(x))

x = tf.convert_to_tensor(x)
print(type(x))

<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
